CREATE TABLE Dashbord(REG_NUMBER INT,
                      Name VARCHAR(50),
					  Class INT,
					  Phase INT);
SELECT * FROM Dashbord;

 CREATE TABLE MARKSHEET1(
    REG_NUMBER INT,
    PHYSICS INT,
    CHEMISTRY INT,
    BIOLOGY INT,
    MATHEMATICS INT,
    SST INT,
    OBTAINED_MARKS INT,
    MAX_MARKS INT,
    PERCENTAGE_SCORE DECIMAL(5,2),
    RANK INT
);

SELECT * FROM MARKSHEET;

SELECT d.REG_NUMBER INT,d.Name ,d.Class,d.Phase
,m.PHYSICS,m.CHEMISTRY,m.BIOLOGY,m.MATHEMATICS,m.SST,
m.OBTAINED_MARKS,m.MAX_MARKS INT,m.PERCENTAGE_SCORE,
m.RANK
FROM Dashbord d
LEFT JOIN
MARKSHEET m
ON d.reg_Number=m.reg_number;